### ISSUE TITLE
put all models under "models" folder at root repo directory - just for cleanliness. 

### ISSUE THREAD

**Issue by ahmedhosny** [modelhub-ai/modelhub#22]
I dont want to move them myself because this will mess up your start scripts?

**Comment by ahmedhosny** [comment]
should we also move the start_scripts in their respective folders? since the docker files will also be there - so everything is in one place? what do you think?

**Comment by michaelschwier** [comment]
I think it makes sense to that when we have the models under s specific folder. Only reason I kept them in a special folder was for automatic discovery, but if we have a specific model folder, containing nothing bu models it should just be as easy to discover from there

**Comment by michaelschwier** [comment]
I'll make the changes today
