### ISSUE TITLE
Make a modelhub pip installable package for startup

### ISSUE THREAD

**Issue by michaelschwier** [modelhub-ai/modelhub#30]
This would replace the current start script and should have the following sub packages (runnable commands essentially):
- start (start a model with various options)
- list (list all models available online)
- [to be extended]

**Comment by michaelschwier** [comment]
Related #37

**Comment by christophbrgr** [comment]
First version here: https://github.com/modelhub-ai/modelhub/commit/1fa2929a70e8ac629dc7368f0fc162ef1a1b3789 

Commands: 
modelhub MODEL 
modelhub-run MODEL 
modelhub-list 

All functionality is retained fully, so one can just use `modelhub` as an alias of `python start.py`
