### ISSUE TITLE
ModelHub demo GIF?

### ISSUE THREAD

**Issue by fedorov** [modelhub-ai/modelhub#32]
I think it would be quite helpful to have a quick gif with a demo of how modelhub works (not internals, just the summary of the web site features), so that it can be featured in the readme, and included in presentation slides. Would be quite handy for me at the moment!

**Comment by ahmedhosny** [comment]
What kind of information would that gif communicate? how to contribute?

**Comment by fedorov** [comment]
No, I was thinking the end user, something describing the concepts from high level. Something I could insert in slide 6 of this slide deck: http://bit.ly/2NlzP4A (to be presented soon, but I am sure I will need to do this in the future again!)

**Comment by ahmedhosny** [comment]
great let me send an email later today.
