### ISSUE TITLE
Starting model notebook does not work if port is taken

### ISSUE THREAD

**Issue by fedorov** [modelhub-ai/modelhub#36]
When a notebook server is already running, (default) port 8888 is taken, and it appears that the server started within the docker is not available, although there are no errors reported on the console.

**Comment by fedorov** [comment]
As a quick fix, maybe there should be a warning to make sure no jupyter notebooks are running prior to starting the model notebook?

**Comment by fedorov** [comment]
For the reference, running the script in sudo mode (and this is on mac) does not fix the issue.

**Comment by michaelschwier** [comment]
This actually seem to be an IP issue on MAC. Docker apparently runs under a different IP than the host system, so the port is actually free, but we have to figure out the correct IP to access the model.

**Comment by michaelschwier** [comment]
start.py now offers options to change ports 27b073676445b6335977318e712b0c7322d3e723
